database:
  mysql:
    host: "192.168.31.215"
    port: 3306
    user: "root"
    password: "root"
    dbname: "hmdp"
    table:
      producer_message_table_name: "tb_seckill_order_local_message"
      consumer_message_table_name: "tb_seckill_order_message_consumption"
  redis:
    address: "192.168.31.215:6379"
    password: ""
    db: 0

api:
  base_url: "http://192.168.31.215:8080"
  prefix:
    auth_code: "/api/user/code"
    login: "/api/user/login"
    voucher: "/api/voucher/seckill"
    purchase: "/api/voucher-order/seckill"

test:
  user:
    base_phone: 18000000000
    user_count: 1000
    auth_file_name: "auths.csv"
    batch_size: 1000
  voucher:
    id: 5
    stock: 100
    purchase_duration_sec: 60 # 购买压力测试持续时间，0代表每个账号只发送一次购买请求


